export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "error-container": "#9f0519",
              "primary-fixed": "#6e9fff",
              "surface-container-lowest": "#000000",
              "on-secondary": "#33005b",
              "primary-dim": "#699cff",
              "secondary-fixed": "#e5c6ff",
              "tertiary-fixed-dim": "#ff73b1",
              "on-secondary-container": "#e9cdff",
              "on-surface": "#dfe4fe",
              "surface-tint": "#85adff",
              "tertiary-dim": "#ff67ad",
              "outline-variant": "#41475b",
              "tertiary-fixed": "#ff8cbc",
              "primary-fixed-dim": "#5391ff",
              "on-tertiary-container": "#2f0018",
              "surface-container": "#11192e",
              "on-surface-variant": "#a5aac2",
              "error-dim": "#d7383b",
              "on-primary-fixed": "#000000",
              "on-error": "#490006",
              "surface": "#070d1f",
              "surface-dim": "#070d1f",
              "secondary-container": "#6f00be",
              "on-background": "#dfe4fe",
              "primary": "#85adff",
              "surface-container-low": "#0c1326",
              "on-primary": "#002c66",
              "surface-bright": "#222b47",
              "on-primary-container": "#002150",
              "inverse-surface": "#faf8ff",
              "on-error-container": "#ffa8a3",
              "on-tertiary": "#4b002a",
              "secondary-dim": "#9c48ea",
              "primary-container": "#6e9fff",
              "inverse-primary": "#005bc4",
              "error": "#ff716c",
              "tertiary-container": "#fa53a4",
              "outline": "#6f758b",
              "surface-container-highest": "#1c253e",
              "on-tertiary-fixed-variant": "#740044",
              "surface-container-high": "#171f36",
              "on-secondary-fixed-variant": "#7511c3",
              "inverse-on-surface": "#4f5469",
              "surface-variant": "#1c253e",
              "on-secondary-fixed": "#4f0089",
              "tertiary": "#ff6daf",
              "on-tertiary-fixed": "#37001d",
              "secondary-fixed-dim": "#dbb4ff",
              "secondary": "#c180ff",
              "background": "#070d1f",
              "on-primary-fixed-variant": "#002a62"
      },
      "borderRadius": {
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Manrope"],
              "body": ["Inter"],
              "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
